import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

// Payment Methods Configuration
type PaymentMethod = 'paypal' | 'bank_transfer';

interface PaymentDetails {
  bookingId: string;
  amount: number;
  customerEmail: string;
  paymentMethod: PaymentMethod;
}

export async function POST(req: Request) {
  try {
    const {
      bookingId,
      amount,
      customerEmail,
      paymentMethod,
    } = await req.json() as PaymentDetails;

    const supabase = await createClient();

    // Create payment record in database
    const { data: paymentData, error: paymentError } = await supabase
      .from('payments')
      .insert({
        booking_id: bookingId,
        amount_czk: amount,
        payment_method: paymentMethod,
        status: 'pending',
        currency: 'CZK',
      })
      .select()
      .single();

    if (paymentError) {
      throw new Error(`Failed to create payment record: ${paymentError.message}`);
    }

    // Process payment based on method
    let result: { url?: string; reference?: string; bankDetails?: any } = {};
    
    switch (paymentMethod) {
      case 'paypal':
        result = await processPayPalPayment(amount, customerEmail, bookingId);
        break;
      case 'bank_transfer':
        result = await processBankTransfer(amount, bookingId);
        break;
      default:
        throw new Error('Invalid payment method');
    }

    // Update payment record with result
    await supabase
      .from('payments')
      .update({
        status: result.url ? 'pending' : 'completed',
        transaction_reference: result.reference,
        processed_at: new Date().toISOString(),
      })
      .eq('id', paymentData.id);

    return NextResponse.json({
      success: true,
      redirectUrl: result.url,
      paymentMethod,
      paymentId: paymentData.id,
      bankDetails: result.bankDetails,
    });
  } catch (error: any) {
    console.error('[Payment Error]:', error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}

// Process PayPal Payment (Placeholder for PayPal SDK integration)
async function processPayPalPayment(
  amount: number,
  customerEmail: string,
  bookingId: string
) {
  // In production, integrate with PayPal SDK
  // This is a placeholder that returns a mock transaction reference
  const transactionRef = `PPL-${bookingId}-${Date.now()}`;
  
  // Return PayPal checkout URL (would be generated by PayPal SDK)
  const paypalUrl = `${process.env.NEXT_PUBLIC_BASE_URL}/booking/paypal?ref=${transactionRef}`;
  
  return { url: paypalUrl, reference: transactionRef };
}

// Process Bank Transfer (Generates invoice)
async function processBankTransfer(amount: number, bookingId: string) {
  const transactionRef = `BANK-${bookingId}-${Date.now()}`;
  
  // Generate payment instructions
  const bankDetails = {
    accountNumber: process.env.BANK_ACCOUNT_NUMBER || '123456789/0800',
    bankCode: process.env.BANK_CODE || '0800',
    reference: transactionRef,
    amount,
    currency: 'CZK',
  };
  
  return {
    url: undefined, // Bank transfer doesn't redirect
    reference: transactionRef,
    bankDetails,
  };
}

// Generate Invoice (Utility function)
export function generateInvoice({
  bookingId,
  amount,
  amountDue,
  paymentMethod,
  transactionRef,
  customerEmail
}: {
  bookingId: string;
  amount: number;
  amountDue: number;
  paymentMethod: string;
  transactionRef: string;
  customerEmail: string;
}) {
  return {
    invoiceId: `INV-${bookingId}-${Date.now()}`,
    bookingId,
    customerEmail,
    amount,
    amountDue,
    paymentMethod,
    transactionRef,
    date: new Date().toISOString(),
    items: [
      {
        description: `Booking Service for ${bookingId}`,
        quantity: 1,
        unitPrice: amount,
        totalPrice: amount,
      },
    ],
    taxes: [
      {
        name: 'VAT',
        rate: 21,
        amount: 0, // Services may be VAT exempt
      },
    ],
    summary: {
      subtotal: amount,
      taxes: 0,
      total: amount,
      paid: amount - amountDue,
      balance: amountDue,
    },
  };
}
